// Code generated by internal/patchformat/gen; DO NOT EDIT.

package patchformat

const (
	FormatVersion                   = 4
	PrefixSize                      = 16
	FooterSize                      = 64
	WindowDescriptorSize            = 88
	IdentityChunkSize    uint64     = 8388608
	WindowCopy           WindowKind = 2
	WindowDeltaRaw       WindowKind = 3
	WindowDeltaZstd      WindowKind = 4
	WindowReplaceRaw     WindowKind = 5
	WindowReplaceZstd    WindowKind = 6
	WindowRun            WindowKind = 8
	WindowSame           WindowKind = 1
	WindowZero           WindowKind = 7
	CodecNone            Codec      = 0
	CodecZstd            Codec      = 1
	OpcodeAddLong        byte       = 7
	OpcodeAddShort       byte       = 6
	OpcodeCopyAbsolute   byte       = 5
	OpcodeCopyAddPair    byte       = 10
	OpcodeCopyDeltaShort byte       = 4
	OpcodeCopyLocalLong  byte       = 3
	OpcodeCopyLocalShort byte       = 2
	OpcodeCopySameShort  byte       = 1
	OpcodeEnd            byte       = 0
	OpcodeRunByte        byte       = 8
	OpcodeZero           byte       = 9
)
